global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
alerting:
  alertmanagers:
    - static_configs:
      - targets: []
      scheme: http
      timeout: 10s
      api_version: v1
scrape_configs:
  - job_name: prometheus
    honor_timestamps: true
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets:
        - localhost:9090
  - job_name: services
    honor_timestamps: true
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets:
        - link_shortener:3333
  - job_name: 'traefik'
    static_configs:
      - targets: ['traefik:8899']
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx-exporter:9113']
  - job_name: 'n8n'
    static_configs:
      - targets: ['n8n:5678']
  # - job_name: 'tempo'
  #   static_configs:
  #     - targets:
  #       - 'tempo:3200'
  # - job_name: 'otel-collector'
  #   static_configs:
  #     - targets: ['otel-collector:8889']
  #     - targets: ['otel-collector:8888']
